### ISSUE TITLE
"Failed to load response data" in chrome

### ISSUE THREAD

**Issue by nhagen** [github/fetch#83]
I'm getting a "Failed to load response data" error in chrome. When I chrome inspect after``xhr.responseType = 'blob'``, ``xhr.responseText`` immediately becomes the following:

`` [Exception: DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').]``

When I change it ``xhr.responseType = ''`` the problem goes away.

Here are the http headers:

```
Remote Address:127.0.0.1:3000
Request URL:http://localhost:3000/api/Orders
Request Method:GET
Status Code:200 OK

Request Headers
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:localhost:3000
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

Response Header
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:8080
Connection:keep-alive
Content-Length:32
Content-Type:application/json; charset=utf-8
Date:Wed, 28 Jan 2015 04:27:25 GMT
ETag:W/"20-c4c67a6b"
Vary:Origin, Accept-Encoding
X-Powered-By:Express
 ```

There is no problem in FF. I'm using fetch via the flux Martyjs library. Could this be a problem with my API endpoint? Can anyone provide any insight into this, or reproduce it?

Let me know what I can provide to be more constructive here.

**Comment by dgraham** [comment]
[We always set](https://github.com/github/fetch/blob/2d2ba78b7c6953817be58a443f783cbfadc68fdf/fetch.js#L284-L286) `responseType` to `blob`, which doesn't seem right. Introduced in https://github.com/github/fetch/pull/60.

@josh

**Comment by josh** [comment]
> We always set responseType to blob, which doesn't seem right. 

Thats definitely what we want to do, but it sounds like `responseText` is incorrectly being accessed *somehow* instead of the general `response` type.

**Comment by josh** [comment]
@nhagen can you post more to reproduce this example.

**Comment by nhagen** [comment]
I'm able to isolate this just inside of marty, but it is resolved as described above.

Following the getting started guide here: http://martyjs.org/guides/getting-started/
```
npm install -g yo generator-marty
mkdir example && cd example
yo marty
yo marty:domain user
npm start
open http://localhost:5000/user/134 in chrome
```

Inspecting the api call to ``http://localhost:5000/api/users/134`` yields ``Failed to load response data``. I did not initially find this after using the yeoman generator, so i was able to get this in my own code and in the autogenerated code.

I'm creating an issue in martyjs in case its a problem with that library at this point. https://github.com/jhollingworth/marty/issues/90

**Comment by msokk** [comment]
Also to note, there is a Chrome devtools bug about not showing blob type XHR's response in Network tab - 
https://code.google.com/p/chromium/issues/detail?id=412401

Example: http://jsfiddle.net/ysangkok/sJxXk/86/

**Comment by adamschoenemann** [comment]
I'm having the same exact problem. The chrome issue appears closed, yet the bug still remains.

**Comment by msokk** [comment]
I think it is not released to stable yet. Chrome Canary works.

**Comment by adamschoenemann** [comment]
Ah, thanks! Chrome Canary works.

**Comment by josh** [comment]
Closing out since this is not an issue with this library.

**Comment by harikishan89** [comment]
Me too have the same issue

**Comment by WangYang-Rex** [comment]
I'm having the same exact problem!

**Comment by bofcarbon1** [comment]
I am running an Angular 4 UI compile with webpack and I just upgraded to zone.js 0.8.4. Got the 'net ERR CONNECTION REFUSED error but only in Google Chrome browser. When I used IE I have no problems. 

The zone.js code and error....

start of code....

    function scheduleTask(task) {
        XMLHttpRequest[XHR_SCHEDULED] = false;
        var data = task.data;
        // remove existing event listener
        var listener = data.target[XHR_LISTENER];
        if (listener) {
            data.target.removeEventListener('readystatechange', listener);
        }
        var newListener = data.target[XHR_LISTENER] = function () {
            if (data.target.readyState === data.target.DONE) {
                // sometimes on some browsers XMLHttpRequest will fire onreadystatechange with
                // readyState=4 multiple times, so we need to check task state here
                if (!data.aborted && XMLHttpRequest[XHR_SCHEDULED] && task.state === 'scheduled') {
                    task.invoke();
                }
            }
        };
        data.target.addEventListener('readystatechange', newListener);
        var storedTask = data.target[XHR_TASK];
        if (!storedTask) {
            data.target[XHR_TASK] = task;
        }
        sendNative.apply(data.target, data.args);  ///' error message Failed to load resource: net::ERR_CONNECTION_REFUSED  ////
        XMLHttpRequest[XHR_SCHEDULED] = true;
        return task;
    }

end of code.............

I don't even know what the scheduled task would be or why zone.js is processing this XHR TASK for data. 
My observable calls are in an injected service and they are the only way that I pass Json data back and forth through http request/responses. All this works fine. Can't figure out why this task attempt is made with no data on Google Chrome.

**Comment by dgraham** [comment]
[Stack Overflow](https://stackoverflow.com) is the best place to ask browser usage questions.
